### ISSUE TITLE
Incorrect temperature readings on Polaris and older

### ISSUE THREAD

**Issue by Datisit** [ChefKissInc/SMCRadeonSensors#12]
**Describe the bug**

As described in the title, the temp reading for my RX 580 constantly jumps to up 127ºC in both iStat Menus and Stats before going back to the correct tempurature at regular intervals.  

**To Reproduce**
1. Check the temperature in monitoring software

**Expected behavior**
Not show the erroneous temperature reading.

**Screenshots**
![Screenshot 2024-05-23 at 17 09 31](https://github.com/ChefKissInc/SMCRadeonSensors/assets/14685/7ec017c2-e5d4-4fae-b432-e22fcdd224b4)
![Screenshot 2024-05-23 at 17 09 07](https://github.com/ChefKissInc/SMCRadeonSensors/assets/14685/b1a25ec2-fc54-4c9b-a64c-92f82cb776e9)

**System Information:**
 - macOS Version: macOS 12.7.4
 - CPU: [e.g. Intel 8700k]

**Additional context**
Happens on version 2.0 but also happened on the previous release.

**Comment by VisualEhrmanntraut** [comment]
Nice catch, thanks for reporting this with enough details. I did a quick look through the Linux source code and I found the error with my code. I will fix it tomorrow, it is midnight over here.

**Comment by VisualEhrmanntraut** [comment]
@Datisit does this work properly?

[SMCRadeonSensors-2.0.0-RELEASE.zip](https://github.com/ChefKissInc/SMCRadeonSensors/files/15442081/SMCRadeonSensors-2.0.0-RELEASE.zip)
