### ISSUE TITLE
RadeonSensor communication failure

### ISSUE THREAD

**Issue by 9thChasingWindGirl** [ChefKissInc/SMCRadeonSensors#16]
Does RadeonSensor need to be used with Radeongadget?

The graphics card I use is AMD 6900XT
![截屏2024-08-25 22 12 42](https://github.com/user-attachments/assets/df6ae194-51ec-4aa8-9ef2-0c13f1d8c475)

**Comment by hg13bs** [comment]
outdated kext, must remove both RadeonSensor.kext and SMCRadeonGPU.kext then get SMCRadeonSensors from releases tab and use an app like [stats](https://github.com/exelban/stats)

**Comment by 9thChasingWindGirl** [comment]
> outdated kext, must remove both RadeonSensor.kext and SMCRadeonGPU.kext then get SMCRadeonSensors from releases tab and use an app like [stats](https://github.com/exelban/stats)

I mistakenly thought SMCRadeonGPU.kext would continue to work with radeongadget, I've changed the app.
